### ISSUE TITLE
Post lost image after public post

### ISSUE THREAD

**Issue by TheKop** [airani/wp-auto-upload#11]
If original website have link image as this type
.....
src="http://xxx.com/thumb/thumb.php?w=555&amp;src=http://yyy.com/2014/10/100-700x400.jpg"
.....
your code will be wrong
it don''t download real image http://yyy.com/2014/10/100-700x400.jpg
So image content after pubish is empty image
I''m not programmer php . But i need it and i already fixed it
Hope you can update for everybody 
Thanks

**Comment by airani** [comment]
@TheKop Can you give me a sample url?
