### ISSUE TITLE
Updated Plugin: Error Occurs on Activation

### ISSUE THREAD

**Issue by Phenie** [airani/wp-auto-upload#20]
Hi there,

I have loved this plugin for many years and updated to v3.1 yesterday only to find there seems to be an error. Perhaps it's just my setup, but activating the plugin causes the following error:

```
Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '[' in .../wp-content/plugins/auto-upload-images/src/ImageUploader.php on line 37
```

Wordpress is up to date at 4.7.3

It seems to be an array calling [0] where the error is occurring.
I attempted to remove the [0] which fixed the error, but instead broke the upload URL.

I hope this can be fixed!

**Comment by airani** [comment]
@Phenie Thank you for reporting
What's your php version? and whats your base url?

**Comment by airani** [comment]
@Phenie I release v3.1.1 please update to this version and try again

**Comment by Phenie** [comment]
Thank you for the quick fix!
Happy to report that it seems to be running smoothly once again!
