### ISSUE TITLE
Issue with Url have redirect

### ISSUE THREAD

**Issue by leekad** [airani/wp-auto-upload#26]
If image url start with http, but the target redirect to https, curl without CURLOPT_FOLLOWLOCATION set to true will return empty string.

please add : curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1); to resolve this issue

Thank you

**Comment by airani** [comment]
Fixed at ac52d11767778fd1033877118da06c976b2f1cfb v3.2
