### ISSUE TITLE
Not working with 4.8.2 with enabled "Image size" option

### ISSUE THREAD

**Issue by tommyhaas1** [airani/wp-auto-upload#31]
If max width and max height is set, path in posts is replaced with missing (image)filename.
This part is failing in return a valid filename:

        // if set max width and height resize image
         if (WpAutoUpload::getOption('max_width') || WpAutoUpload::getOption('max_height')) {
             $width = WpAutoUpload::getOption('max_width');
             $height = WpAutoUpload::getOption('max_height');
             $image_resized = image_make_intermediate_size($image_path, $width, $height);
             $image_url = urldecode($upload_dir['url'] . '/' . $image_resized['file']);
         }

**Comment by airani** [comment]
Please test again with new version released
