### ISSUE TITLE
Great plugin, but fails on complex img URLs

### ISSUE THREAD

**Issue by horizon89** [airani/wp-auto-upload#35]
Hello,

This is a great plugin. But I have to say that it fails to upload/include image files which have complex url structures. Here is an example:

https://images.unsplash.com/photo-1511988617509-a57c8a288659?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjI1NDQxfQ&s=e91ec3d695b7e406f29dd80a706fc0ad&w=1000

Just thought to let you know.

Thanks again for this great piece of software.

**Comment by airani** [comment]
Fixed at ac52d11767778fd1033877118da06c976b2f1cfb v3.2
