### ISSUE TITLE
uploading all images to wp-content/uploads/-000

### ISSUE THREAD

**Issue by TKList** [airani/wp-auto-upload#36]
uploading all images to wp-content/uploads/-000 instead of date directory

**Comment by Budget101** [comment]
> uploading all images to wp-content/uploads/-000 instead of date directory

It would be helpful if you'd provide a url of your original image filename and then a url of the changed filename.

I've experienced this on SOME images the url to the image being IMPORTED was:
`[IMG]https://i.pinimg.com/564x/73/47/18/734718d1e603d63e16f9ab4315d3e182.jpg[/IMG] `

and it returned the following url after import:

`<img src="http://MYDOMAINHERE.com/wp-content/uploads/-000//1/734718d1e603d63e16f9ab4315d3e182.jpg" alt=" ">`

In addition to it inserting the image in a -000 file, it also appended an additional / 

it would appear that it stripped the following information

`/564x/73/47/18/`

which I believe can be remedied with the fix that @hacker365 shared here:
https://github.com/hackers365/wp-auto-upload/commit/c3b6b8a9551f1dfa44c214a0f57157ee8a07778d
