### ISSUE TITLE
Support srcset attribute of img tag

### ISSUE THREAD

**Issue by 4n70w4** [airani/wp-auto-upload#40]
Hi! Your plagin don't download images from srcset attribute.
https://www.w3schools.com/tags/att_source_srcset.asp
https://html.com/attributes/img-srcset/

Example:
`<img class="aligncenter size-large wp-image-29" src="https://mysite.com/5ba585c425254.png" width="640" height="239" srcset="https://mysite.com/5ba585c425254.png 1024w, https://originsite.com/5ba585c425254-150x56.png 150w, https://originsite.com/5ba585c425254-300x112.png 300w, https://originsite.com/5ba585c425254-768x287.png 768w, https://originsite.com/5ba585c425254-640x239.png 640w, https://originsite.com/5ba585c425254-980x366.png 980w, https://originsite.com/EW5vYUlm9xuJnGOZBZN1F38Hw.png 1308w" sizes="(max-width: 640px) 100vw, 640px" />`

**Comment by 4n70w4** [comment]
@airani any news?

**Comment by airani** [comment]
This feature added to new version released v3.2.2 please update. Closes at https://github.com/airani/wp-auto-upload/commit/6af797a61597244f899a29d14e962ce473e665a2
