### ISSUE TITLE
Imports images, but the image source url in my post is missing the filename

### ISSUE THREAD

**Issue by melzor** [airani/wp-auto-upload#44]
Hi, the plugin works for importing the image to ML, but the url of the source image in the post ends up being something like:

http://mydomain.com/wp-content/uploads/2019/01/

instead of 

http://mydomain.com/wp-content/uploads/2019/01/myfilename.jpg

Any idea what's wrong?

I left my settings default, except I excluded all other post types except for the Post type.

**Comment by Budget101** [comment]
What do you have listed for settings for your **Image Name** in your "Auto Upload Image Settings"? 

yourdomain.com/wp-admin/options-general.php?page=auto-upload

**Comment by mrkurou** [comment]
I'm having the same issue. The image files are download and inserted in the server, but the URL inside the post misses file-name.jpg.

The plugin worked a couple of time as expected, but not more. I was using as Image Name: %postname%. Tried other things, and no hope.

Running on Wordpress 5.1

**Comment by melzor** [comment]
@Budget101 I am using the plugin's default settings
