### ISSUE TITLE
Ends attachments with a .php extension

### ISSUE THREAD

**Issue by Budget101** [airani/wp-auto-upload#45]
This works great, except for 1 major problem, it renames attachments ending them with a .php extension - if you click on an image within a post- it shows a page of scrambled coded. 

If you try to save an image within a post, it saves as a .php  

how do you make it save attachments as .jpg .png .gif files the way they were initially uploaded?

**Comment by Budget101** [comment]
The .php can be stripped by changing the following:
`public function getFilename()
    {
        $filename = basename($this->url);
//preg_match('/(.*)?(\.+[^.]*)$/', $filename, $name_parts); // REMOVED THIS LINE & Replaced with the next line
        preg_match('#(.+?)\?(.+[^.]*)$#*)$/', $filename, $name_parts);
        $this->filename = $name_parts[0];  // Changed this from 1 to 0
        $postfix = $name_parts[2];
        if (preg_match('/^(\.[^?]*)\?.*/i', $postfix, $postfix_extra)) {
            $postfix = $postfix_extra[1];
        }
        $filename = $this->resolvePattern(WpAutoUpload::getOption('image_name'));
        return $filename . $postfix;
    }`

This **STILL doesn't show the correct image extension**, gif, jpg, png, but at least it doesn't lead to a garbled php code when someone tries to preview the image in its own window.

**Comment by airani** [comment]
Fixed at ac52d11767778fd1033877118da06c976b2f1cfb v3.2

**Comment by Budget101** [comment]
> Fixed at [ac52d11](https://github.com/airani/wp-auto-upload/commit/ac52d11767778fd1033877118da06c976b2f1cfb) v3.2

Unfortunately, after applying the fix, it doesn't even attempt to save external attachments at all now. 

`http://www.example.com/attachment.php?attachmentid=271`

remains the same. However, If I go to the link and right click to download, the image saves as 

filename: cheddartaters.jpg

**Comment by airani** [comment]
@Budget101  I released v3.2 at now in wp plugins please update officially and test again. if you have any problems again please tell me with your wp version and php version.
Thank you
