### ISSUE TITLE
Improvement of URL matching

### ISSUE THREAD

**Issue by Malaiac** [airani/wp-auto-upload#48]
So I got multiple errors from ImageUploader::getFilename()

Some URL, like
`https://lh3.googleusercontent.com/nFZVza6phshhw7VJ7-h2WP5Rrw1ASB1RV27pCDNXQYoIqmK-3pfL7BMCuQZ8mqfYf32ywCebbZdrtGCPHMOX6r1ZGy-_yPzcUkzykwYRqwA09cwLRfoxDJmaprQJyK6IUgWuYwuM`
do not work with the function

I propose an improvement :
`    /**
     * Return custom image name with user rules
     * @return string Custom file name
     */
    public function getFilename()
    {
        $filename = basename($this->url);
        if(preg_match('#(.+?)\?(.+[^.]*)$#', $filename, $name_parts)) {
            $this->filename = $name_parts[1];
            $postfix = $name_parts[2];
            if (preg_match('/^(\.[^?]*)\?.*/i', $postfix, $postfix_extra)) {
                $postfix = $postfix_extra[1];
            }
        }
        else {
            $this->filename = $filename;
            $postfix = '';
        }     
        $filename = $this->resolvePattern(WpAutoUpload::getOption('image_name'));
        return $filename . $postfix;
    }`

Note the change of regex from
`/(.*)?(\.+[^.]*)$/`
to
`#(.+?)\?(.+[^.]*)$#`

**Comment by Malaiac** [comment]
The change of regex will solve https://github.com/airani/wp-auto-upload/issues/35

**Comment by Budget101** [comment]
You added "else "  as well, was that intentional as it is not in the original code  . . .

`else { 
 $this->filename = $filename; $postfix = ''; }`

**Comment by Malaiac** [comment]
The else is for URL not matching the regex, aka URL without query strings. In that case, filename should be the full filename of the URL
