### ISSUE TITLE
New features suggestions

### ISSUE THREAD

**Issue by menathor** [airani/wp-auto-upload#5]
Hey guys,

Great plugin! It would be great to see 2 features added to the plugin:

1. A %timestamp% option in the filename to call time(); (unix timestamp). This is a great way of adding a unique string of numbers to the filename to avoid duplicate names if uploaded on the same day.

2. Option to "set first image as featured image" option added to the plugin. This would be very useful for the people who remote publish photos to wordpress from IFTTT (eg. instagram or facebook photos). We need to set the featured image of the post to get correct thumbnails appearing when sharing links on social media.

**Comment by menathor** [comment]
Also, would be great if the plugin used wp_unique_filename, so if there are duplicates wordpress will automatically rename filenames filename, filename_1, filename_2 etc.

**Comment by airani** [comment]
It's feature added to v3.0

**Comment by chicag0** [comment]
Any update on "Option to "set first image as featured image"?

Also, I would love to only download the first XX photos, rather than all, as I have some posts with hundreds of photos

**Comment by airani** [comment]
@chicag0 some plugins exists for doing this work in wordpress. please search it
