### ISSUE TITLE
Uploading bbpress external Images

### ISSUE THREAD

**Issue by Budget101** [airani/wp-auto-upload#52]
The images in the bbpress forums upload, but the only way to get them to upload to the media library is to click on Dashboard>Topics>All Topics> Screen Options, set to 50 (any more than that returns errors), Highlight all> Edit> Update.

While this is okay for small boards, I just imported over 400K posts. Is there a way to force it to BULK Update automatically? It's really not feasible to manually edit 8,000 Times.

**Comment by airani** [comment]
Please test again with new version released
