### ISSUE TITLE
Not working for me for a Page from CDN

### ISSUE THREAD

**Issue by HeadStudios** [airani/wp-auto-upload#55]
I have a page with an image on it like so:
https://d418bv7mr3wfv.cloudfront.net/s3/W1siZiIsIjIwMTgvMTAvMTEvMjMvMDIvNTUvMjQxL1dlIGFzayBxdWVzdGlvbnMgdGhhdCBjcmVhdGUgbWFnaWNhbCBjb25uZWN0aW9ucyAoNCkucG5nIl1d
However after activating the plugin and updating the page the image is still redirecting to the Cloudfront CDN

**Comment by treminaor** [comment]
The cURL in ImageUploader.php::save() needs to have the option for following redirects enabled for CDN and old attachment-style CMS links to work.

`curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);`

**Comment by airani** [comment]
Fixed in v3.2
