### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by chrisbacke** [airani/wp-auto-upload#70]
Details: WP current version (5.3.2) as of this date.
Plugin version 3.2.2
Using Classic Editor plugin. Divi themes

Already done standard checks such as deactivate all other plugins, changing to default theme (Twenty Twenty and Twenty Nineteen, in this case),...

Images to be pulled from are mainly from Medium.com, and links go to the direct photo.

Help! =)

**Comment by TheSimArchitect** [comment]
Yes, same here. Image is still hot linked instead of uploaded and replaced with local. 😟

**Comment by airani** [comment]
fixed at 7756053
