### ISSUE TITLE
مشکل پس از تغییر تنظیمات

### ISSUE THREAD

**Issue by arssearsse** [airani/wp-auto-upload#81]
سلام. وقت شما بخیر. 
از بابت این نرم افزار رایگان متشکرم.

من این پلاگین را نصب کردم و استفاده می کردم. سپس برخی از سایتها را مستثنی کردم و برخی تیکها را زدم.
بعد که نصف سایتهای مستثنی شده را حذف کردم و فقط نصف سایتهای مستثنی شده ماند الان هرچه عکس از سایتهای مختلف میگذارم ناتوان از مکش آن است و همان یو آر ال سایت اصلی را در پست ها استفاده میکند.
چند سایت دیگر دارم که تنظیمات این پلاگین را تغییر ندادم ودارد کار میکند.
خواهشمندم بررسی بفرمایید در پلاگین باگ نباشد.
مرسی

**Comment by arssearsse** [comment]
post
page
attachment
revision
customize_changeset 

موارد فوق تیک ندارد

**Comment by arssearsse** [comment]
سلام
مشکل حل شد.
دایرکتوری آپلود را 777 کردم مشکل حل شد. فقط در همان هاست در دامن ههای دیگر وردپرس و همین پلاگین نصب است ولی دایرکتوری آپلود 755 است ولی بی مشکل عکس توسط همین پلاگین آپلود می شود! آیا می دانید مشکل چیست؟

**Comment by airani** [comment]
سلام
خیر متوجه مشکلتون نشدم احتمالا برای سطح دسترسی ها بوده
شما فارسی زبان هستید؟

**Comment by arssearsse** [comment]
سلام . بله ایرانی هستم.
تشکر از این پلاگین عالی که نوشتین.


بله مشکل پرمیشن فولدر آپلود بود 777 کردم پلاگین کار کرد.
اما گویا خود وردپرس باید برای نوشتن 777 کند و بعد دوباره 755 کند.
سایر سایتها که از ورد پرس و افزونه شما استفاده می کند در پنل هاست پرمیشن آنها 775 است.
